import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
mkdirSync('test-results', { recursive: true });
const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1366, height: 900 }, reducedMotion: 'reduce' });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const position = () => page.getByTestId('train-T01').getAttribute('transform');
try {
    await page.goto(process.env.TEST_URL || 'http://127.0.0.1:5173', { waitUntil: 'networkidle' });
    await page.getByTestId('track-P12').waitFor();
    assert.equal(await page.locator('.sv-track').count(), 12);
    assert.equal(await page.locator('.sv-train').count(), 7);
    assert.match(await page.getByTestId('track-P04').getAttribute('aria-label'), /закрыт/);
    assert.equal(await page.locator('.sv-track-hatch').count(), 1);
    const first = await position();
    await page.waitForTimeout(350);
    assert.equal(await position(), first, 'pause freezes train');
    await page.getByRole('button', { name: '▶ Запустить', exact: true }).click();
    await page.waitForTimeout(350);
    assert.notEqual(await position(), first, 'train animates');
    await page.getByRole('button', { name: '×10', exact: true }).click();
    assert.equal(await page.getByTestId('train-T01').count(), 1);
    await page.getByRole('button', { name: 'Ⅱ Пауза', exact: true }).click();
    const paused = await position();
    await page.waitForTimeout(350);
    assert.equal(await position(), paused);
    await page.getByTestId('track-P04').focus();
    await page.keyboard.press('Enter');
    assert.equal(await page.getByTestId('track-P04').getAttribute('aria-pressed'), 'true');
    await page.getByTestId('train-T03').click();
    assert.equal(await page.getByTestId('train-T03').getAttribute('aria-pressed'), 'true');
    await page.getByRole('button', { name: 'Показать прогноз', exact: true }).click();
    assert.equal(await page.locator('.sv-route-preview').count(), 1);
    assert.equal(await page.locator('.sv-train').count(), 7, 'preview adds no ghost trains');
    await page.getByRole('button', { name: 'Показать на схеме →', exact: true }).click();
    assert.match(await page.getByTestId('track-P04').getAttribute('class'), /is-conflict/);
    await page.getByRole('button', { name: 'Увеличить масштаб', exact: true }).click();
    assert.notEqual(await page.locator('.sv-map').getAttribute('viewBox'), '0 0 1400 900');
    const beforeDrag = await page.locator('.sv-map').getAttribute('viewBox');
    const bounds = await page.locator('.sv-map').boundingBox();
    await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
    await page.mouse.down();
    await page.mouse.move(bounds.x + bounds.width / 2 - 70, bounds.y + bounds.height / 2 - 40, { steps: 5 });
    await page.mouse.up();
    assert.notEqual(await page.locator('.sv-map').getAttribute('viewBox'), beforeDrag);
    await page.getByRole('button', { name: 'Показать всю станцию', exact: true }).click();
    await page.getByRole('button', { name: 'История', exact: true }).click();
    const historical = await position();
    await page.waitForTimeout(350);
    assert.equal(await position(), historical);
    assert.equal(await page.getByRole('button', { name: '▶ Запустить', exact: true }).isDisabled(), true);
    await page.getByRole('button', { name: 'Вернуться в онлайн', exact: true }).click();
    await page.getByRole('button', { name: '▶ Запустить', exact: true }).click();
    await page.getByRole('button', { name: 'Отключить связь', exact: true }).click();
    const offline = await position();
    await page.waitForTimeout(350);
    assert.equal(await position(), offline);
    await page.getByRole('button', { name: 'Восстановить связь', exact: true }).click();
    await page.getByRole('button', { name: '↺ Сброс', exact: true }).click();
    assert.equal(await position(), 'translate(40 450)');
    assert.equal(await page.locator('.sv-route-preview').count(), 0);
    await page.reload({ waitUntil: 'networkidle' });
    await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
    await page.setViewportSize({ width: 1366, height: 768 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: 'test-results/laptop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
    assert.deepEqual(errors, []);
    console.log('PASS: 12 tracks, selection by keyboard/click, animation, pause, speed, preview, conflict, zoom/pan, history, disconnect/reconnect, reset, desktop/mobile layout; no browser exceptions.');
}
finally {
    await browser.close();
}
